In [1]:
from __future__ import annotations
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tqdm import tqdm
from loguru import logger

ROOT = Path.cwd().resolve()

while ROOT != ROOT.parent and not (ROOT / "app").is_dir():
    ROOT = ROOT.parent

if not (ROOT / "app").is_dir():
    raise RuntimeError(
        "Папка app не найдена. "
        "Откройте Notebook внутри репозитория CloudMarks."
    )

sys.path.insert(0, str(ROOT))

In [2]:
from app.cross_points.CrossPointExacter import CrossPointExacter


exacter = CrossPointExacter(
    file_path="../data/t1/1_A_10_2_l.txt",
    show_scans=False,
    normal_k=8,
    min_points_per_plane=100,
    cluster_eps=0.08,
)

point = exacter.calculate_intersect_point()
point.name = "A_10_2_l"

df_point = point.to_dataframe()
display(df_point)

2026-08-29 12:32:17.845 | INFO     | app.cross_points.CrossPointExacter:_initialize:262 - Подготовка виртуальной точки: scan='1_A_10_2_l', N=5931, reference=None
2026-08-29 12:32:17.845 | INFO     | app.cross_points.CrossPointExacter:_segment_local_planes:299 - Вычисление нормалей: k=8
2026-08-29 12:32:17.921 | INFO     | app.cross_points.CrossPointExacter:_segment_local_planes:305 - Классификация направлений нормалей: n_classes=3
2026-08-29 12:32:17.955 | INFO     | app.cross_points.CrossPointExacter:_segment_local_planes:319 - Размеры классов нормалей: {0: 1111, 1: 4703, 2: 117}
2026-08-29 12:32:17.966 | DEBUG    | app.cross_points.CrossPointExacter:_select_component:442 - Плоскость 1: DBSCAN-компонента 0, точек=1111
2026-08-29 12:32:17.968 | INFO     | app.cross_points.CrossPointExacter:_segment_local_planes:356 - Плоскость 1/3: класс нормалей 0, выбрано 1111 точек
2026-08-29 12:32:18.004 | DEBUG    | app.cross_points.CrossPointExacter:_select_component:442 - Плоскость 2: DBSCAN-компонента 0, точек=4702
2026-08-29 12:32:18.012 | INFO     | app.cross_points.CrossPointExacter:_segment_local_planes:356 - Плоскость 2/3: класс нормалей 1, выбрано 4702 точек
2026-08-29 12:32:18.013 | DEBUG    | app.cross_points.CrossPointExacter:_select_component:442 - Плоскость 3: DBSCAN-компонента 0, точек=115
2026-08-29 12:32:18.014 | INFO     | app.cross_points.CrossPointExacter:_segment_local_planes:356 - Плоскость 3/3: класс нормалей 2, выбрано 115 точек
2026-08-29 12:32:18.014 | INFO     | app.cross_points.CrossPointExacter:calculate_planes:540 - Аппроксимация плоскости 1/3: 1111 точек
2026-08-29 12:32:18.020 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=1111, rmse=0.002726
2026-08-29 12:32:18.026 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=1006, rmse=0.001507
2026-08-29 12:32:18.031 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=951, rmse=0.001018
2026-08-29 12:32:18.037 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=908, rmse=0.000879
2026-08-29 12:32:18.041 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=872, rmse=0.000810
2026-08-29 12:32:18.046 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=845, rmse=0.000767
2026-08-29 12:32:18.051 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=816, rmse=0.000725
2026-08-29 12:32:18.056 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=790, rmse=0.000687
2026-08-29 12:32:18.060 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=767, rmse=0.000655
2026-08-29 12:32:18.064 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=744, rmse=0.000624
2026-08-29 12:32:18.069 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=725, rmse=0.000599
2026-08-29 12:32:18.075 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=709, rmse=0.000580
2026-08-29 12:32:18.080 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=699, rmse=0.000568
2026-08-29 12:32:18.084 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=693, rmse=0.000562
2026-08-29 12:32:18.087 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=686, rmse=0.000554
2026-08-29 12:32:18.092 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=681, rmse=0.000548
2026-08-29 12:32:18.096 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=676, rmse=0.000542
2026-08-29 12:32:18.100 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=672, rmse=0.000538
2026-08-29 12:32:18.103 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=668, rmse=0.000533
2026-08-29 12:32:18.108 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=666, rmse=0.000531
2026-08-29 12:32:18.110 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneLSMFitter, points=665, rmse=0.000529
2026-08-29 12:32:18.110 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=IterativePlaneFitter, points=665, rmse=0.000529
2026-08-29 12:32:18.110 | SUCCESS  | app.cross_points.CrossPointExacter:calculate_planes:563 - Плоскость 1/3: inliers=665, RMSE=0.000529
2026-08-29 12:32:18.111 | INFO     | app.cross_points.CrossPointExacter:calculate_planes:540 - Аппроксимация плоскости 2/3: 4702 точек
2026-08-29 12:32:18.125 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=4702, rmse=0.007910
2026-08-29 12:32:18.144 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=4677, rmse=0.001535
2026-08-29 12:32:18.161 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=4443, rmse=0.001221
2026-08-29 12:32:18.179 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=4230, rmse=0.001074
2026-08-29 12:32:18.196 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=4029, rmse=0.000977
2026-08-29 12:32:18.211 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=3852, rmse=0.000902
2026-08-29 12:32:18.224 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=3737, rmse=0.000857
2026-08-29 12:32:18.239 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=3663, rmse=0.000831
2026-08-29 12:32:18.252 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=3606, rmse=0.000812
2026-08-29 12:32:18.266 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=3580, rmse=0.000804
2026-08-29 12:32:18.283 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=3564, rmse=0.000799
2026-08-29 12:32:18.295 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=3559, rmse=0.000798
2026-08-29 12:32:18.310 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=3554, rmse=0.000796
2026-08-29 12:32:18.323 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=3552, rmse=0.000795
2026-08-29 12:32:18.337 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=3550, rmse=0.000795
2026-08-29 12:32:18.352 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=3548, rmse=0.000794
2026-08-29 12:32:18.358 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneLSMFitter, points=3548, rmse=0.000794
2026-08-29 12:32:18.359 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=IterativePlaneFitter, points=3548, rmse=0.000794
2026-08-29 12:32:18.359 | SUCCESS  | app.cross_points.CrossPointExacter:calculate_planes:563 - Плоскость 2/3: inliers=3548, RMSE=0.000794
2026-08-29 12:32:18.359 | INFO     | app.cross_points.CrossPointExacter:calculate_planes:540 - Аппроксимация плоскости 3/3: 115 точек
2026-08-29 12:32:18.361 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=115, rmse=0.011490
2026-08-29 12:32:18.363 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=113, rmse=0.001662
2026-08-29 12:32:18.364 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=112, rmse=0.000649
2026-08-29 12:32:18.366 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneL1Fitter, points=111, rmse=0.000616
2026-08-29 12:32:18.366 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=PlaneLSMFitter, points=111, rmse=0.000557
2026-08-29 12:32:18.366 | INFO     | app.scan.ScanPlane:fit_plane_to_scan:84 - Аппроксимация плоскости завершена: fitter=IterativePlaneFitter, points=111, rmse=0.000557
2026-08-29 12:32:18.367 | SUCCESS  | app.cross_points.CrossPointExacter:calculate_planes:563 - Плоскость 3/3: inliers=111, RMSE=0.000557
2026-08-29 12:32:18.367 | DEBUG    | app.cross_points.CrossPointExacter:_check_parallel:97 - Угол между плоскостями 1 и 2: 89.735°
2026-08-29 12:32:18.367 | DEBUG    | app.cross_points.CrossPointExacter:_check_parallel:97 - Угол между плоскостями 1 и 3: 89.850°
2026-08-29 12:32:18.367 | DEBUG    | app.cross_points.CrossPointExacter:_check_parallel:97 - Угол между плоскостями 2 и 3: 88.837°
2026-08-29 12:32:18.368 | SUCCESS  | app.cross_points.CrossPointExacter:diagnose_geometry:594 - Геометрия устойчива: det(N)=-0.999780, cond(N)=1.02

,name,x,y,z,status,reliable_accuracy,mse,plane_1_mse,plane_2_mse,plane_3_mse,sigma_x,sigma_y,sigma_z,ellipsoid_confidence,ellipsoid_a,ellipsoid_b,ellipsoid_c
0,A_10_2_l,99.313348,107.766052,8.153626,GOOD,True,0.000189,0.000529,0.000794,0.000557,0.000179,0.000015,0.000057,0.95,0.000501,0.00016,0.000042

In [3]:
print(
    f"{point.name}: "
    f"X={point.x:.6f}, "
    f"Y={point.y:.6f}, "
    f"Z={point.z:.6f}, "
    f"status={point.status}"
)

print(point)

A_10_2_l: X=99.313348, Y=107.766052, Z=8.153626, status=GOOD
CrossPoint (name=A_10_2_l, status=GOOD, x=99.313348, y=107.766052, z=8.153626, plane_mses=[0.000529, 0.000794, 0.000557], mse=0.000189, sigma_xyz=(0.000179, 0.000015, 0.000057))

In [4]:
print(f"Имя точки: {point.name}")
print()

print("Координаты, м")
print(f"  X: {point.x:.6f}")
print(f"  Y: {point.y:.6f}")
print(f"  Z: {point.z:.6f}")
print()

print("Статус")
print(f"  Геометрия: {point.status}")
print(
    "  Точность: "
    f"{'надёжная' if point.reliable_accuracy else 'ненадёжная'}"
)
print()

if point.mse is not None:
    print("Средняя квадратическая ошибка")
    print(f"  RMSE: {point.mse:.6f} м")
    print()

if point.planes_mse is not None:
    print("RMSE аппроксимации плоскостей")

    for index, plane_mse in enumerate(
        point.planes_mse,
        start=1,
    ):
        print(
            f"  Плоскость {index}: "
            f"{plane_mse:.6f} м"
        )

    print()

if point.reliable_accuracy and point.sigma_xyz is not None:
    sigma_x, sigma_y, sigma_z = point.sigma_xyz

    print("Средние квадратические погрешности координат")
    print(f"  σX: {sigma_x:.6f} м")
    print(f"  σY: {sigma_y:.6f} м")
    print(f"  σZ: {sigma_z:.6f} м")
    print()

if point.reliable_accuracy and point.cov_xyz is not None:
    print("Ковариационная матрица координат, м²")
    print(point.cov_xyz)
    print()

if point.reliable_accuracy and point.ellipsoid is not None:
    semi_axes = point.ellipsoid["semi_axes"]
    confidence = point.ellipsoid["confidence"]

    print(
        "Эллипсоид погрешностей "
        f"(доверительная вероятность {confidence:.0%})"
    )
    print(f"  Большая полуось: {semi_axes[0]:.6f} м")
    print(f"  Средняя полуось: {semi_axes[1]:.6f} м")
    print(f"  Малая полуось:   {semi_axes[2]:.6f} м")

Имя точки: A_10_2_l

Координаты, м
  X: 99.313348
  Y: 107.766052
  Z: 8.153626

Статус
  Геометрия: GOOD
  Точность: надёжная

Средняя квадратическая ошибка
  RMSE: 0.000189 м

RMSE аппроксимации плоскостей
  Плоскость 1: 0.000529 м
  Плоскость 2: 0.000794 м
  Плоскость 3: 0.000557 м

Средние квадратические погрешности координат
  σX: 0.000179 м
  σY: 0.000015 м
  σZ: 0.000057 м

Ковариационная матрица координат, м²
[[ 3.21442012e-08 -3.36973585e-11 -9.24727633e-11]
 [-3.36973585e-11  2.30164278e-10  1.46813357e-11]
 [-9.24727633e-11  1.46813357e-11  3.28643337e-09]]

Эллипсоид погрешностей (доверительная вероятность 95%)
  Большая полуось: 0.000501 м
  Средняя полуось: 0.000160 м
  Малая полуось:   0.000042 м

In [5]:
output_path = ROOT / "output" / f"{point.name}.csv"
output_path.parent.mkdir(parents=True, exist_ok=True)

df_point.to_csv(
    output_path,
    index=False,
    encoding="utf-8",
    float_format="%.6f",
)

df_point
output_path

PosixPath('/Users/mihailvystrcil/Documents/My Programms/CloudMarks/output/A_10_2_l.csv')

In [6]:
output_path = ROOT / "output" / f"{point.name}.xlsx"
output_path.parent.mkdir(parents=True, exist_ok=True)

point.to_dataframe().to_excel(
    output_path,
    index=False,
    sheet_name="VirtualPoint",
)

print(f"Excel-файл сохранён: {output_path}")

Excel-файл сохранён: /Users/mihailvystrcil/Documents/My Programms/CloudMarks/output/A_10_2_l.xlsx

In [7]:
from loguru import logger
from app.batch.SingleScanPointExtractor import (
    SingleScanPointExtractor,
)

logger.remove()

extractor = SingleScanPointExtractor.from_files(
    scan_path="../data/t2/scan_2335.las",
    reference_points_path="../data/t2/vse_tochki.txt",
    default_radius=0.25,
    min_neighborhood_points=800,
    min_points_per_plane=150,
    normal_k=8,
    cluster_eps=0.08,
)

results = extractor.run(
    show_progress=True
).to_dataframe()

results

[1/3] Загрузка скана...

Загрузка scan_2335.las: 100%|██████████| 4337974/4337974 [00:10<00:00, 399295.89точка/s]

готово: 4,337,974 точек
[2/3] Построение пространственного индекса...

готово
Опорных точек: 196

[3/3] Извлечение точек: 100%|██████████| 196/196 [00:09<00:00, 19.60точка/s]

Готово: 35/196 надёжных точек

,name,reference_x,reference_y,reference_z,radius,neighborhood_points,reference_distance,status,message,x,y,z,geometry_status,reliable_accuracy,sigma_x,sigma_y,sigma_z
0,A_10_2_l,99.3127,107.7533,8.1465,0.25,4682,NaN,UNRELIABLE,Для плоскости 3 выделено недостаточно точек: 9...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN
1,A_10_2_r,101.0595,107.7900,8.1438,0.25,4798,NaN,UNRELIABLE,Точка ненадёжна: geometry_status=PARALLEL.,100.516326,107.765778,8.154636,PARALLEL,False,NaN,NaN,NaN
2,A_10_3_l,99.3061,107.7612,11.6365,0.25,3261,NaN,UNRELIABLE,Точка ненадёжна: geometry_status=PARALLEL.,99.677008,107.764067,11.646920,PARALLEL,False,NaN,NaN,NaN
3,A_10_3_r,101.0720,107.7561,11.6403,0.25,3303,0.175203,SUCCESS,OK,100.897215,107.765188,11.648275,GOOD,True,0.005155,0.000046,0.000063
4,A_10_4_l,99.2973,107.7508,15.3065,0.25,2330,NaN,UNRELIABLE,Для плоскости 3 выделено недостаточно точек: 4...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,A_9_6_r,98.0572,107.7900,22.4644,0.25,1247,NaN,UNRELIABLE,Для плоскости 3 выделено недостаточно точек: 5...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN
192,A_9_7_l,96.2911,107.7365,25.9726,0.25,1043,NaN,UNRELIABLE,Для плоскости 1 выделено недостаточно точек: 9...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN
193,A_9_7_r,98.0578,107.7522,25.9854,0.25,1007,NaN,UNRELIABLE,Для плоскости 3 выделено недостаточно точек: 3...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN
194,A_9_8_l,96.2968,107.7472,29.5982,0.25,914,NaN,UNRELIABLE,Для плоскости 1 выделено недостаточно точек: 6...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN
195,A_9_8_r,98.0622,107.7513,29.5912,0.25,864,NaN,UNRELIABLE,Точка ненадёжна: geometry_status=PARALLEL.,97.781380,107.750269,29.590506,PARALLEL,False,NaN,NaN,NaN

In [8]:
points = results.query("status == 'SUCCESS'")[
    [
        "name",
        "x",
        "y",
        "z",
        "sigma_x",
        "sigma_y",
        "sigma_z",
    ]
]

points

         name           x           y          z   sigma_x   sigma_y   sigma_z
3    A_10_3_r  100.897215  107.765188  11.648275  0.005155  0.000046  0.000063
15   A_11_2_r  104.086872  107.765617   8.155802  0.000107  0.000020  0.000088
17   A_11_3_r  104.087458  107.760094  11.644738  0.000091  0.000040  0.000073
19   A_11_4_r  104.087433  107.758718  15.326739  0.000163  0.000030  0.000116
21   A_11_5_r  104.087030  107.749718  18.848946  0.000153  0.000036  0.000110
29   A_12_2_r  107.086962  107.761244   8.143266  0.000100  0.000046  0.000145
31   A_12_3_r  107.086054  107.755811  11.650559  0.000111  0.000028  0.000138
33   A_12_4_r  107.097349  107.760624  15.330984  0.000122  0.000040  0.000107
43   A_13_2_r  110.097429  107.767612   8.154826  0.000124  0.000034  0.000102
45   A_13_3_r  110.098202  107.757693  11.642005  0.000124  0.000039  0.000112
47   A_13_4_r  110.095009  107.758588  15.324953  0.000145  0.000056  0.000173
49   A_13_5_r  110.098829  107.760535  18.857881  0.000160  0.000058  0.000191
59   A_14_3_r  113.109282  107.758286  11.639563  0.000146  0.000041  0.000213
61   A_14_4_r  113.112339  107.756032  15.323318  0.000163  0.000051  0.000208
63   A_14_5_r  113.108389  107.754340  18.849203  0.000226  0.000067  0.000230
73   A_15_3_r  116.119058  107.759340  11.637136  0.000204  0.000059  0.000265
128   A_5_3_l   84.277296  107.763682  11.639420  0.000230  0.000050  0.000202
140   A_6_2_l   87.277170  107.765046   8.146423  0.000209  0.000044  0.000229
142   A_6_3_l   87.277758  107.754696  11.637535  0.000194  0.000055  0.000155
144   A_6_4_l   87.275819  107.765929  15.329825  0.000203  0.000053  0.000151
146   A_6_5_l   87.273850  107.752070  18.849665  0.000163  0.000093  0.000264
156   A_7_3_l   90.288755  107.753194  11.639532  0.000131  0.000040  0.000151
158   A_7_4_l   90.531353  107.755991  15.310814  0.008288  0.000109  0.000202
160   A_7_5_l   90.275011  107.759195  18.864844  0.000189  0.000041  0.000174
162   A_7_6_l   90.288005  107.747240  22.465509  0.000271  0.000072  0.000223
168   A_8_2_l   93.295383  107.765262   8.146030  0.000137  0.000029  0.000116
170   A_8_3_l   93.288898  107.760423  11.641659  0.000114  0.000048  0.000101
172   A_8_4_l   93.286807  107.756175  15.314860  0.000129  0.000041  0.000129
174   A_8_5_l   93.279147  107.758370  18.857812  0.000138  0.000060  0.000154
176   A_8_6_l   93.283252  107.752499  22.462067  0.000370  0.000044  0.000157
178   A_8_7_l   93.279624  107.742894  25.985288  0.000502  0.000052  0.000169
182   A_9_2_l   96.310404  107.765496   8.145327  0.000094  0.000025  0.000066
184   A_9_3_l   96.291049  107.764712  11.640507  0.000106  0.000037  0.000076
186   A_9_4_l   96.292826  107.761300  15.310663  0.000127  0.000033  0.000118
188   A_9_5_l   96.287573  107.750749  18.846284  0.000229  0.000033  0.000124

In [9]:
output = ROOT / "output" / "t2_virtual_points.xlsx"
output.parent.mkdir(exist_ok=True)

points.to_excel(
    output,
    index=False,
    sheet_name="VirtualPoints",
)

print(f"Найдено точек: {len(points)}")
print(f"Файл: {output}")

Найдено точек: 35
Файл: /Users/mihailvystrcil/Documents/My Programms/CloudMarks/output/t2_virtual_points.xlsx

In [10]:
from loguru import logger
from app.batch.PointPairComparisonRunner import (
    PointPairComparisonRunner,
)

logger.remove()
runner = PointPairComparisonRunner.from_files(
    epoch1_path="../data/t2/scan_2335_split_a.las",
    epoch2_path="../data/t2/scan_2335_split_b.las",
    default_radius=0.5,
    min_neighborhood_points=800,
    min_points_per_plane=200,
    normal_k=8,
    cluster_eps=0.08,
)

results = runner.run_from_reference_file(
    reference_points_path="../data/t2/vse_tochki.txt",
    show_progress=True,
)

deformations = results.query(
    "processing_status == 'SUCCESS'"
)

deformations[
    [
        "name",
        "epoch1_x",
        "epoch1_y",
        "epoch1_z",
        "epoch2_x",
        "epoch2_y",
        "epoch2_z",
        "dx",
        "dy",
        "dz",
        "displacement_mm",
    ]
]

Загрузка scan_2335_split_a.las: 100%|██████████| 2168981/2168981 [00:05<00:00, 397114.93точка/s]
Загрузка scan_2335_split_b.las: 100%|██████████| 2168993/2168993 [00:05<00:00, 402507.21точка/s]
Обработка точек: 100%|██████████| 392/392 [00:32<00:00, 11.92эпоха/s, OK=22]

Анализ деформаций... готово: 22/196 пар

,name,epoch1_x,epoch1_y,epoch1_z,epoch2_x,epoch2_y,epoch2_z,dx,dy,dz,displacement_mm
15,A_11_2_r,104.086941,107.765804,8.155451,104.087232,107.765756,8.154809,0.000291,-0.000048,-0.000642,0.705993
17,A_11_3_r,104.087522,107.761363,11.645304,104.087849,107.761343,11.645753,0.000326,-0.000021,0.000449,0.555403
19,A_11_4_r,104.086554,107.758426,15.326991,104.087550,107.758429,15.327224,0.000996,0.000003,0.000233,1.022641
29,A_12_2_r,107.086856,107.764275,8.144277,107.086757,107.764300,8.144054,-0.000100,0.000025,-0.000222,0.244881
35,A_12_5_r,107.104637,107.758165,18.859744,107.104598,107.758931,18.859190,-0.000039,0.000765,-0.000553,0.945240
43,A_13_2_r,110.095698,107.767389,8.154570,110.095993,107.767510,8.154915,0.000294,0.000121,0.000346,0.469925
47,A_13_4_r,110.094647,107.758220,15.325413,110.094444,107.758247,15.325274,-0.000203,0.000027,-0.000140,0.247795
49,A_13_5_r,110.100289,107.759545,18.857836,110.099659,107.759429,18.857636,-0.000630,-0.000116,-0.000200,0.670625
59,A_14_3_r,113.107032,107.758719,11.639462,113.107167,107.758788,11.640212,0.000135,0.000069,0.000750,0.764873
61,A_14_4_r,113.111217,107.756944,15.323205,113.112512,107.756972,15.322930,0.001295,0.000028,-0.000275,1.323787
75,A_15_4_r,116.123340,107.761501,15.325462,116.123304,107.761354,15.326378,-0.000037,-0.000147,0.000916,0.928374
130,A_5_4_l,84.274849,107.765892,15.326952,84.275447,107.765856,15.326525,0.000598,-0.000036,-0.000426,0.735258
140,A_6_2_l,87.277433,107.765260,8.146435,87.277597,107.765133,8.147430,0.000164,-0.000127,0.000995,1.016448
142,A_6_3_l,87.277766,107.754919,11.639021,87.277535,107.755392,11.638572,-0.000231,0.000473,-0.000449,0.692051
144,A_6_4_l,87.276157,107.765579,15.329406,87.275486,107.765690,15.329443,-0.000671,0.000111,0.000037,0.681597
146,A_6_5_l,87.274429,107.753278,18.849417,87.274349,107.753731,18.849923,-0.000080,0.000452,0.000507,0.684068
154,A_7_2_l,90.290928,107.769016,8.156551,90.291254,107.768919,8.156051,0.000326,-0.000097,-0.000500,0.604391
158,A_7_4_l,90.290830,107.757393,15.313509,90.290896,107.757522,15.313931,0.000067,0.000129,0.000422,0.446492
160,A_7_5_l,90.274823,107.758612,18.865091,90.275050,107.758633,18.865742,0.000227,0.000021,0.000651,0.689512
170,A_8_3_l,93.287532,107.762734,11.642862,93.287453,107.762685,11.642366,-0.000078,-0.000049,-0.000496,0.504372
172,A_8_4_l,93.288544,107.757429,15.314927,93.289724,107.757481,15.315250,0.001180,0.000052,0.000323,1.224340
174,A_8_5_l,93.279598,107.756537,18.857535,93.279873,107.756817,18.856913,0.000276,0.000279,-0.000623,0.735913

In [11]:
deformations

,name,reference_x,reference_y,reference_z,radius,epoch1_neighborhood_points,epoch2_neighborhood_points,epoch1_reference_distance,epoch2_reference_distance,pair_distance,...,sigma_dz,sigma_displacement,sigma_displacement_mm,t_value,p_value_t,significant_t,chi2_value,p_value_chi2,significant_chi2,analysis_reliable
15,A_11_2_r,104.0839,107.7565,8.1510,0.5,7019,6981,0.010753,0.010549,0.000706,...,0.000117,0.000118,0.118393,5.963117,2.474709e-09,True,40.481242,8.424288e-09,True,True
17,A_11_3_r,104.0912,107.7559,11.6290,0.5,4984,5030,0.017584,0.017931,0.000555,...,0.000117,0.000111,0.111380,4.986543,6.146928e-07,True,25.757542,1.071979e-05,True,True
19,A_11_4_r,104.0877,107.7516,15.3142,0.5,3412,3463,0.014543,0.014707,0.001023,...,0.000121,0.000190,0.189858,5.386344,7.190515e-08,True,29.927446,1.429415e-06,True,True
29,A_12_2_r,107.0840,107.7573,8.1347,0.5,4887,4877,0.012187,0.012004,0.000245,...,0.000114,0.000114,0.114385,2.140853,3.228593e-02,True,5.064232,1.671537e-01,False,True
35,A_12_5_r,107.1023,107.7518,18.8447,0.5,2213,2212,0.016501,0.016313,0.000945,...,0.000207,0.000140,0.140275,6.738465,1.600686e-11,True,96.724894,7.862990e-21,True,True
43,A_13_2_r,110.0912,107.7668,8.1473,0.5,3142,3186,0.008569,0.009026,0.000470,...,0.000131,0.000149,0.149384,3.145745,1.656642e-03,True,22.755789,4.540363e-05,True,True
47,A_13_4_r,110.0968,107.7900,15.3104,0.5,2081,2083,0.035214,0.035143,0.000248,...,0.000209,0.000191,0.190989,1.297429,1.944836e-01,False,1.942935,5.843349e-01,False,True
49,A_13_5_r,110.0993,107.7900,18.8398,0.5,1703,1701,0.035409,0.035395,0.000671,...,0.000234,0.000273,0.272601,2.460097,1.388996e-02,True,9.871257,1.969281e-02,True,True
59,A_14_3_r,113.1109,107.7541,11.6370,0.5,1858,1844,0.006509,0.006799,0.000765,...,0.000255,0.000253,0.253224,3.020536,2.523276e-03,True,10.205284,1.689938e-02,True,True
61,A_14_4_r,113.1084,107.7900,15.3194,0.5,1591,1589,0.033393,0.033470,0.001324,...,0.000240,0.000226,0.226299,5.849715,4.924170e-09,True,34.359909,1.663166e-07,True,True
75,A_15_4_r,116.1223,107.7401,15.3071,0.5,1168,1140,0.028218,0.028712,0.000928,...,0.000359,0.000355,0.354566,2.618341,8.835835e-03,True,9.777957,2.055102e-02,True,True
130,A_5_4_l,84.2754,107.7651,15.3211,0.5,1180,1188,0.005931,0.005478,0.000735,...,0.000321,0.000320,0.320390,2.294886,2.173966e-02,True,5.428858,1.429562e-01,False,True
140,A_6_2_l,87.2765,107.7577,8.1438,0.5,2094,2116,0.008060,0.008345,0.001016,...,0.000223,0.000220,0.220111,4.617887,3.876672e-06,True,27.220245,5.293479e-06,True,True
142,A_6_3_l,87.2764,107.7454,11.6296,0.5,1882,1879,0.013462,0.013477,0.000692,...,0.000231,0.000170,0.170247,4.064980,4.803658e-05,True,45.329189,7.875949e-10,True,True
144,A_6_4_l,87.2804,107.7582,15.3195,0.5,1601,1602,0.013061,0.013383,0.000682,...,0.000199,0.000245,0.245451,2.776910,5.487830e-03,True,11.494857,9.329970e-03,True,True
146,A_6_5_l,87.2725,107.7448,18.8348,0.5,1335,1326,0.017007,0.017660,0.000684,...,0.000279,0.000217,0.217008,3.152276,1.620029e-03,True,30.951552,8.702504e-07,True,True
154,A_7_2_l,90.2898,107.7683,8.1480,0.5,3334,3330,0.008654,0.008204,0.000604,...,0.000196,0.000182,0.181796,3.324555,8.855992e-04,True,14.407857,2.399420e-03,True,True
158,A_7_4_l,90.2911,107.7553,15.3110,0.5,2127,2148,0.003278,0.003684,0.000446,...,0.000205,0.000198,0.197517,2.260525,2.378867e-02,True,12.712402,5.301691e-03,True,True
160,A_7_5_l,90.2708,107.7524,18.8425,0.5,1724,1715,0.023773,0.024436,0.000690,...,0.000231,0.000229,0.228581,3.016489,2.557204e-03,True,9.232106,2.635891e-02,True,True
170,A_8_3_l,93.2926,107.7543,11.6356,0.5,3841,3876,0.012229,0.011940,0.000504,...,0.000135,0.000135,0.135027,3.735335,1.874658e-04,True,15.590833,1.375421e-03,True,True
172,A_8_4_l,93.2794,107.7464,15.3012,0.5,2779,2768,0.019841,0.020659,0.001224,...,0.000172,0.000226,0.225829,5.421535,5.908954e-08,True,31.693011,6.074051e-07,True,True
174,A_8_5_l,93.2889,107.7900,18.8412,0.5,2236,2238,0.038381,0.037809,0.000736,...,0.000209,0.000202,0.201791,3.646909,2.654142e-04,True,20.031212,1.672329e-04,True,True

In [12]:
deformations = (
    results.query("processing_status == 'SUCCESS'")
    .sort_values(
        by="displacement_mm",
        ascending=False,
        kind="stable",
    )
    .reset_index(drop=True)
)

deformations[
    [
        "name",
        "epoch1_x",
        "epoch1_y",
        "epoch1_z",
        "epoch2_x",
        "epoch2_y",
        "epoch2_z",
        "dx",
        "dy",
        "dz",
        "displacement_mm",
    ]
].round(4)

,name,epoch1_x,epoch1_y,epoch1_z,epoch2_x,epoch2_y,epoch2_z,dx,dy,dz,displacement_mm
0,A_14_4_r,113.1112,107.7569,15.3232,113.1125,107.7570,15.3229,0.0013,0.0000,-0.0003,1.3238
1,A_8_4_l,93.2885,107.7574,15.3149,93.2897,107.7575,15.3153,0.0012,0.0001,0.0003,1.2243
2,A_11_4_r,104.0866,107.7584,15.3270,104.0876,107.7584,15.3272,0.0010,0.0000,0.0002,1.0226
3,A_6_2_l,87.2774,107.7653,8.1464,87.2776,107.7651,8.1474,0.0002,-0.0001,0.0010,1.0164
4,A_12_5_r,107.1046,107.7582,18.8597,107.1046,107.7589,18.8592,-0.0000,0.0008,-0.0006,0.9452
5,A_15_4_r,116.1233,107.7615,15.3255,116.1233,107.7614,15.3264,-0.0000,-0.0001,0.0009,0.9284
6,A_14_3_r,113.1070,107.7587,11.6395,113.1072,107.7588,11.6402,0.0001,0.0001,0.0007,0.7649
7,A_8_5_l,93.2796,107.7565,18.8575,93.2799,107.7568,18.8569,0.0003,0.0003,-0.0006,0.7359
8,A_5_4_l,84.2748,107.7659,15.3270,84.2754,107.7659,15.3265,0.0006,-0.0000,-0.0004,0.7353
9,A_11_2_r,104.0869,107.7658,8.1555,104.0872,107.7658,8.1548,0.0003,-0.0000,-0.0006,0.7060
10,A_6_3_l,87.2778,107.7549,11.6390,87.2775,107.7554,11.6386,-0.0002,0.0005,-0.0004,0.6921
11,A_7_5_l,90.2748,107.7586,18.8651,90.2750,107.7586,18.8657,0.0002,0.0000,0.0007,0.6895
12,A_6_5_l,87.2744,107.7533,18.8494,87.2743,107.7537,18.8499,-0.0001,0.0005,0.0005,0.6841
13,A_6_4_l,87.2762,107.7656,15.3294,87.2755,107.7657,15.3294,-0.0007,0.0001,0.0000,0.6816
14,A_13_5_r,110.1003,107.7595,18.8578,110.0997,107.7594,18.8576,-0.0006,-0.0001,-0.0002,0.6706
15,A_7_2_l,90.2909,107.7690,8.1566,90.2913,107.7689,8.1561,0.0003,-0.0001,-0.0005,0.6044
16,A_11_3_r,104.0875,107.7614,11.6453,104.0878,107.7613,11.6458,0.0003,-0.0000,0.0004,0.5554
17,A_8_3_l,93.2875,107.7627,11.6429,93.2875,107.7627,11.6424,-0.0001,-0.0000,-0.0005,0.5044
18,A_13_2_r,110.0957,107.7674,8.1546,110.0960,107.7675,8.1549,0.0003,0.0001,0.0003,0.4699
19,A_7_4_l,90.2908,107.7574,15.3135,90.2909,107.7575,15.3139,0.0001,0.0001,0.0004,0.4465
20,A_13_4_r,110.0946,107.7582,15.3254,110.0944,107.7582,15.3253,-0.0002,0.0000,-0.0001,0.2478
21,A_12_2_r,107.0869,107.7643,8.1443,107.0868,107.7643,8.1441,-0.0001,0.0000,-0.0002,0.2449